using CalendarAppRazor.Data;
using CalendarAppRazor.Model;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;


namespace CalendarAppRazor.Pages.InviteCodes
{
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> userManager;

        public IEnumerable<InviteCode> InviteCodes { get; set; }

        public IndexModel(ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _db = db;
            this.userManager = userManager;
        }

        public void OnGet()
        {
            //Only display the invite codes generated by the signed in user.
            InviteCodes = new List<InviteCode>();
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            foreach (var inviteCode in _db.InviteCodes)
            {
                if (inviteCode.ownerId == userId)
                {
                    InviteCodes = InviteCodes.Append(inviteCode);
                }
            }
        }
    }
}
