using CalendarAppRazor.Data;
using CalendarAppRazor.Model;
using CalendarAppRazor.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Security.Claims;

/*
 * We shall be able to review invite codes generated by us,
 * see how many pictures are provided,
 * and view calendars as they're finished.
 * Bonus: make the calendars downloadable.
 */

namespace CalendarAppRazor.Pages.ManageInviteCodes
{
    [Authorize]
    public class IndexModel : PageModel
    {
        private readonly ApplicationDbContext _db;
        private readonly UserManager<IdentityUser> userManager;

        public IEnumerable<ManageInviteCodeModel> InviteCodes { get; set; }

        public IndexModel(ApplicationDbContext db, UserManager<IdentityUser> userManager)
        {
            _db = db;
            this.userManager = userManager;
        }

        public void OnGet()
        {
            //Only display the invite codes generated by the signed in user.
            InviteCodes = new List<ManageInviteCodeModel>();
            var userId = this.User.FindFirstValue(ClaimTypes.NameIdentifier);
            foreach (var inviteCode in _db.InviteCodes)
            {
                if (inviteCode.ownerId == userId)
                {
                    //calculate num of pictures for that code
                    int numOfPictures = numOfPicturesForTheCode(inviteCode);
                    bool isComplete = (numOfPictures == 12);
                    //check if num == 12 and assign to a bool
                    //create view model
                    var model = new ManageInviteCodeModel()
                    {
                        Code = inviteCode.Code,
                        numberOfPictures = numOfPictures,
                        isCalendarReady = isComplete
                    };
                    InviteCodes = InviteCodes.Append(model);
                }
            }
        }

        //Helper method to calculate number of pictures
        private int numOfPicturesForTheCode(InviteCode ic)
        {
            int result = 0;
            foreach(var mppair in _db.MonthPicturePairs)
            {
                if(mppair.Code == ic.Code)
                {
                    result += 1;
                }
            }
            return result;
        }
    }
}

